-- 027_wellbeing_program_30_days.sql — Programme Bien-être V1
-- Additif et idempotent : aucune table historique n'est supprimée.
CREATE TABLE IF NOT EXISTS wellbeing_programs (
    user_id UUID PRIMARY KEY REFERENCES accounts(user_id),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    reminder_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_type TEXT NOT NULL DEFAULT 'wellbeing_daily',
    reminder_text TEXT NOT NULL DEFAULT 'Tes 5 actions Bien-être du jour t’attendent 🌙',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS wellbeing_program_advice (
    id INTEGER PRIMARY KEY,
    text TEXT NOT NULL,
    category TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS wellbeing_program_days (
    user_id UUID NOT NULL REFERENCES accounts(user_id),
    day_number INTEGER NOT NULL CHECK (day_number BETWEEN 1 AND 30),
    local_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (user_id, day_number)
);
CREATE TABLE IF NOT EXISTS wellbeing_program_actions (
    user_id UUID NOT NULL REFERENCES accounts(user_id),
    day_number INTEGER NOT NULL,
    action_slot INTEGER NOT NULL CHECK (action_slot BETWEEN 1 AND 5),
    advice_id INTEGER NOT NULL REFERENCES wellbeing_program_advice(id),
    text_snapshot TEXT NOT NULL,
    category TEXT NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, day_number, action_slot),
    FOREIGN KEY (user_id, day_number) REFERENCES wellbeing_program_days(user_id, day_number)
);
CREATE INDEX IF NOT EXISTS idx_wellbeing_program_actions_user_day
ON wellbeing_program_actions(user_id, day_number);
CREATE TABLE IF NOT EXISTS wellbeing_program_ebook_config (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    title TEXT NOT NULL,
    subtitle TEXT NOT NULL,
    pdf_url TEXT,
    version TEXT NOT NULL DEFAULT '1',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO wellbeing_program_ebook_config (id, title, subtitle, pdf_url, version, active)
VALUES (1, '30 jours pour prendre soin de soi', 'Le petit guide Bien-être Auryel', NULL, '1', TRUE)
ON CONFLICT (id) DO NOTHING;
INSERT INTO wellbeing_program_advice (id, text, category, is_active) VALUES
        (1, 'Marche 10 minutes aujourd’hui.', 'mouvement', TRUE),
        (2, 'Prends quelques minutes à l’air libre.', 'mouvement', TRUE),
        (3, 'Étire doucement tes épaules et ton dos.', 'mouvement', TRUE),
        (4, 'Monte quelques escaliers à ton rythme.', 'mouvement', TRUE),
        (5, 'Fais une courte promenade après un repas.', 'mouvement', TRUE),
        (6, 'Bouge pendant cinq minutes entre deux activités.', 'mouvement', TRUE),
        (7, 'Choisis un trajet à pied si cela t’est possible.', 'mouvement', TRUE),
        (8, 'Danse sur une chanson que tu aimes.', 'mouvement', TRUE),
        (9, 'Prends le temps de respirer en marchant.', 'mouvement', TRUE),
        (10, 'Fais quelques mouvements qui te font du bien.', 'mouvement', TRUE),
        (11, 'Bois régulièrement de l’eau aujourd’hui.', 'hydratation', TRUE),
        (12, 'Garde un verre d’eau près de toi.', 'hydratation', TRUE),
        (13, 'Commence ta journée par un verre d’eau.', 'hydratation', TRUE),
        (14, 'Prends une pause pour boire tranquillement.', 'hydratation', TRUE),
        (15, 'Pense à boire avant d’avoir très soif.', 'hydratation', TRUE),
        (16, 'Ajoute de l’eau à un moment calme de ta journée.', 'hydratation', TRUE),
        (17, 'Emporte une bouteille si tu sors.', 'hydratation', TRUE),
        (18, 'Remplace une boisson sucrée par de l’eau si tu en as envie.', 'hydratation', TRUE),
        (19, 'Observe simplement ce qui t’aide à boire davantage.', 'hydratation', TRUE),
        (20, 'Fais de l’hydratation un petit repère de ta journée.', 'hydratation', TRUE),
        (21, 'Prends un repas sans écran.', 'alimentation', TRUE),
        (22, 'Mange plus lentement pendant quelques minutes.', 'alimentation', TRUE),
        (23, 'Ajoute un fruit ou un légume à ton repas.', 'alimentation', TRUE),
        (24, 'Prépare un repas simple avec ce que tu as déjà.', 'alimentation', TRUE),
        (25, 'Assieds-toi pour manger sans te presser.', 'alimentation', TRUE),
        (26, 'Écoute ta faim et ta satiété avec bienveillance.', 'alimentation', TRUE),
        (27, 'Choisis aujourd’hui un aliment qui te fait plaisir.', 'alimentation', TRUE),
        (28, 'Prends le temps de savourer la première bouchée.', 'alimentation', TRUE),
        (29, 'Fais une pause avant de reprendre une seconde portion.', 'alimentation', TRUE),
        (30, 'Rends un repas un peu plus simple que d’habitude.', 'alimentation', TRUE),
        (31, 'Essaie de te coucher un peu plus tôt si tu le peux.', 'sommeil', TRUE),
        (32, 'Éloigne ton téléphone quelques minutes avant de dormir.', 'sommeil', TRUE),
        (33, 'Prépare calmement les choses dont tu auras besoin demain.', 'sommeil', TRUE),
        (34, 'Baisse la lumière en fin de journée.', 'sommeil', TRUE),
        (35, 'Accorde-toi un moment calme avant le coucher.', 'sommeil', TRUE),
        (36, 'Observe ce qui facilite ton repos ce soir.', 'sommeil', TRUE),
        (37, 'Aère ta chambre quelques minutes.', 'sommeil', TRUE),
        (38, 'Laisse une activité en suspens pour demain.', 'sommeil', TRUE),
        (39, 'Choisis une heure douce pour ralentir.', 'sommeil', TRUE),
        (40, 'Remercie-toi d’avoir pris soin de ton repos.', 'sommeil', TRUE),
        (41, 'Assieds-toi cinq minutes au calme.', 'calme', TRUE),
        (42, 'Fais trois respirations lentes.', 'calme', TRUE),
        (43, 'Observe les sons autour de toi.', 'calme', TRUE),
        (44, 'Laisse passer une pensée sans la suivre.', 'calme', TRUE),
        (45, 'Accorde-toi un temps sans obligation.', 'calme', TRUE),
        (46, 'Pose les pieds au sol et relâche les épaules.', 'calme', TRUE),
        (47, 'Regarde par la fenêtre quelques instants.', 'calme', TRUE),
        (48, 'Fais une pause avant de répondre à un message.', 'calme', TRUE),
        (49, 'Choisis un endroit où tu te sens tranquille.', 'calme', TRUE),
        (50, 'Termine cette pause par une respiration profonde.', 'calme', TRUE),
        (51, 'Accorde-toi 10 minutes sans téléphone.', 'deconnexion', TRUE),
        (52, 'Désactive une notification qui peut attendre.', 'deconnexion', TRUE),
        (53, 'Pose ton téléphone pendant une courte pause.', 'deconnexion', TRUE),
        (54, 'Évite les écrans pendant ton prochain repas.', 'deconnexion', TRUE),
        (55, 'Choisis un moment sans consulter les réseaux.', 'deconnexion', TRUE),
        (56, 'Laisse une conversation numérique pour plus tard.', 'deconnexion', TRUE),
        (57, 'Regarde autour de toi plutôt que ton écran.', 'deconnexion', TRUE),
        (58, 'Mets ton téléphone en silencieux pendant quelques minutes.', 'deconnexion', TRUE),
        (59, 'Profite d’un trajet sans faire défiler ton écran.', 'deconnexion', TRUE),
        (60, 'Termine la journée par un moment hors ligne.', 'deconnexion', TRUE),
        (61, 'Lis au moins cinq pages d’un livre.', 'lecture', TRUE),
        (62, 'Relis un passage que tu apprécies.', 'lecture', TRUE),
        (63, 'Découvre quelques pages avant de dormir.', 'lecture', TRUE),
        (64, 'Lis un article qui nourrit ta curiosité.', 'lecture', TRUE),
        (65, 'Choisis une lecture sans lien avec le travail.', 'lecture', TRUE),
        (66, 'Prends un livre avec toi pour une pause.', 'lecture', TRUE),
        (67, 'Lis lentement une page qui t’interpelle.', 'lecture', TRUE),
        (68, 'Accorde à ta lecture toute ton attention.', 'lecture', TRUE),
        (69, 'Note une idée qui t’est venue en lisant.', 'lecture', TRUE),
        (70, 'Lis quelques lignes au lieu de faire défiler ton écran.', 'lecture', TRUE),
        (71, 'Range un petit espace autour de toi.', 'environnement', TRUE),
        (72, 'Aère une pièce quelques minutes.', 'environnement', TRUE),
        (73, 'Prépare un coin calme pour ta prochaine pause.', 'environnement', TRUE),
        (74, 'Remets à sa place une seule chose.', 'environnement', TRUE),
        (75, 'Jette ou recycle ce qui n’a plus d’usage.', 'environnement', TRUE),
        (76, 'Ouvre les rideaux et laisse entrer la lumière.', 'environnement', TRUE),
        (77, 'Nettoie une petite surface, sans tout entreprendre.', 'environnement', TRUE),
        (78, 'Choisis un objet qui rend ton espace plus agréable.', 'environnement', TRUE),
        (79, 'Libère une chaise ou un coin où te poser.', 'environnement', TRUE),
        (80, 'Fais de ton environnement un appui simple aujourd’hui.', 'environnement', TRUE),
        (81, 'Appelle ou écris à quelqu’un qui compte pour toi.', 'relations', TRUE),
        (82, 'Demande sincèrement des nouvelles à une personne.', 'relations', TRUE),
        (83, 'Envoie un message de gratitude.', 'relations', TRUE),
        (84, 'Propose un moment simple à partager.', 'relations', TRUE),
        (85, 'Prends le temps d’écouter sans préparer ta réponse.', 'relations', TRUE),
        (86, 'Dis clairement merci pour une petite attention.', 'relations', TRUE),
        (87, 'Réponds à un message que tu repousses.', 'relations', TRUE),
        (88, 'Accorde une présence entière à une conversation.', 'relations', TRUE),
        (89, 'Partage quelque chose qui t’a fait sourire.', 'relations', TRUE),
        (90, 'Laisse une personne savoir qu’elle compte pour toi.', 'relations', TRUE),
        (91, 'Note une chose positive de ta journée.', 'gratitude', TRUE),
        (92, 'Écris trois petites choses que tu apprécies.', 'gratitude', TRUE),
        (93, 'Remarque un moment agréable, même bref.', 'gratitude', TRUE),
        (94, 'Souviens-toi d’une personne qui t’a aidé.', 'gratitude', TRUE),
        (95, 'Prends une photo mentale d’un instant apaisant.', 'gratitude', TRUE),
        (96, 'Reconnais un effort que tu as fait récemment.', 'gratitude', TRUE),
        (97, 'Dis-toi une phrase encourageante.', 'gratitude', TRUE),
        (98, 'Observe ce qui a été plus facile aujourd’hui.', 'gratitude', TRUE),
        (99, 'Garde une trace d’un détail qui t’a fait du bien.', 'gratitude', TRUE),
        (100, 'Termine la journée en reconnaissant ce qui a compté.', 'gratitude', TRUE),
        (101, 'Fais aujourd’hui une petite chose que tu repousses.', 'organisation', TRUE),
        (102, 'Choisis une seule priorité pour les prochaines heures.', 'organisation', TRUE),
        (103, 'Écris les trois choses essentielles de ta journée.', 'organisation', TRUE),
        (104, 'Prépare une tâche avant de commencer.', 'organisation', TRUE),
        (105, 'Découpe une tâche importante en une première étape.', 'organisation', TRUE),
        (106, 'Accorde cinq minutes à ce qui attend depuis longtemps.', 'organisation', TRUE),
        (107, 'Supprime une tâche qui n’est plus nécessaire.', 'organisation', TRUE),
        (108, 'Laisse un peu d’espace entre deux rendez-vous.', 'organisation', TRUE),
        (109, 'Termine une petite tâche avant d’en commencer une autre.', 'organisation', TRUE),
        (110, 'Félicite-toi d’avoir avancé, même modestement.', 'organisation', TRUE),
        (111, 'Marche jusqu’à un endroit proche au lieu de prendre un transport.', 'mouvement', TRUE),
        (112, 'Étire tes jambes après être resté assis.', 'mouvement', TRUE),
        (113, 'Fais quelques pas pendant une pause.', 'mouvement', TRUE),
        (114, 'Choisis un mouvement doux qui te convient aujourd’hui.', 'mouvement', TRUE),
        (115, 'Prends une boisson et bois-la lentement.', 'hydratation', TRUE),
        (116, 'Remplis ton verre avant de commencer une nouvelle activité.', 'hydratation', TRUE),
        (117, 'Garde de l’eau accessible pendant ta journée.', 'hydratation', TRUE),
        (118, 'Prends une pause hydratation en pleine conscience.', 'hydratation', TRUE),
        (119, 'Prépare un encas simple si tu en as besoin.', 'alimentation', TRUE),
        (120, 'Mange assis et accorde-toi quelques minutes.', 'alimentation', TRUE),
        (121, 'Ajoute une couleur différente à ton assiette.', 'alimentation', TRUE),
        (122, 'Pose tes couverts quelques instants pendant ton repas.', 'alimentation', TRUE),
        (123, 'Éteins une lumière vive avant de ralentir.', 'sommeil', TRUE),
        (124, 'Choisis une routine calme pour la fin de journée.', 'sommeil', TRUE),
        (125, 'Prépare ton espace de repos avec simplicité.', 'sommeil', TRUE),
        (126, 'Note ce qui pourra attendre demain matin.', 'sommeil', TRUE),
        (127, 'Ferme les yeux et écoute ta respiration une minute.', 'calme', TRUE),
        (128, 'Observe une sensation agréable autour de toi.', 'calme', TRUE),
        (129, 'Fais une pause avant de passer à la suite.', 'calme', TRUE),
        (130, 'Accueille un moment de silence dans ta journée.', 'calme', TRUE),
        (131, 'Laisse ton téléphone dans une autre pièce quelques minutes.', 'deconnexion', TRUE),
        (132, 'Choisis une activité sans écran pour ta prochaine pause.', 'deconnexion', TRUE),
        (133, 'Regarde dehors avant d’ouvrir une application.', 'deconnexion', TRUE),
        (134, 'Accorde-toi un moment sans notifications.', 'deconnexion', TRUE),
        (135, 'Lis quelques pages dans un endroit confortable.', 'lecture', TRUE),
        (136, 'Choisis un texte qui te fait apprendre quelque chose.', 'lecture', TRUE),
        (137, 'Pose ton livre après une lecture agréable.', 'lecture', TRUE),
        (138, 'Partage une phrase intéressante de ta lecture.', 'lecture', TRUE),
        (139, 'Plie ou range quelques vêtements.', 'environnement', TRUE),
        (140, 'Nettoie doucement l’endroit où tu commences ta journée.', 'environnement', TRUE),
        (141, 'Place un objet utile à portée de main.', 'environnement', TRUE),
        (142, 'Crée un petit espace qui t’invite à faire une pause.', 'environnement', TRUE),
        (143, 'Envoie un mot simple à une personne que tu apprécies.', 'relations', TRUE),
        (144, 'Partage un souvenir agréable avec quelqu’un.', 'relations', TRUE),
        (145, 'Demande de l’aide pour une petite chose si nécessaire.', 'relations', TRUE),
        (146, 'Prends des nouvelles sans attendre une occasion particulière.', 'relations', TRUE),
        (147, 'Célèbre une petite avancée de ta journée.', 'gratitude', TRUE),
        (148, 'Écris ce que tu aimerais retenir de cette journée.', 'gratitude', TRUE),
        (149, 'Commence par deux minutes d’une tâche importante.', 'organisation', TRUE),
        (150, 'Prépare une chose qui rendra demain plus simple.', 'organisation', TRUE)
ON CONFLICT (id) DO NOTHING;
