-- 036_exercise_catalog.sql — catalogue Bien-être V1.
-- Catalogue serveur dédié aux exercices : additif, rejouable et indépendant
-- des méditations, vidéos Réveil, ebooks et récompenses.

CREATE TABLE IF NOT EXISTS exercise_catalog (
    id               UUID         PRIMARY KEY,
    slug             TEXT         NOT NULL UNIQUE,
    title            TEXT         NOT NULL,
    category         TEXT         NOT NULL,
    description      TEXT         NOT NULL DEFAULT '',
    duration_seconds INTEGER      NOT NULL CHECK (duration_seconds > 0),
    level            TEXT         NOT NULL,
    steps            JSONB        NOT NULL CHECK (jsonb_typeof(steps) = 'array' AND jsonb_array_length(steps) > 0),
    precautions      TEXT         NOT NULL DEFAULT '',
    sort_order       INTEGER      NOT NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    published_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version          INTEGER      NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_exercise_catalog_active
ON exercise_catalog (is_active, category, sort_order, id);

INSERT INTO exercise_catalog (
    id, slug, title, category, description, duration_seconds, level,
    steps, precautions, sort_order
) VALUES
    ('00000000-0036-4036-8000-000000000001'::uuid, 'respiration-accordee', 'Respiration accordée', 'breathing', 'Un rythme simple pour retrouver une respiration plus régulière et un peu d’espace intérieur.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Observe ton souffle sans le changer.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Laisse l’inspiration et l’expiration devenir de longueur proche.","seconds":120},{"order":3,"title":"Terminer","instruction":"Termine par trois respirations naturelles et remarque ce qui a changé.","seconds":null}]'::jsonb, 'Si une sensation désagréable apparaît, reprends ton rythme naturel et arrête si elle persiste.', 1),
    ('00000000-0036-4036-8000-000000000002'::uuid, 'souffle-en-carre-doux', 'Souffle en carré doux', 'breathing', 'Quatre temps égaux, sans forcer, pour poser ton attention sur le mouvement du souffle.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Inspire doucement sur quatre temps.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Garde une pause très courte ou passe-la si besoin.","seconds":120},{"order":3,"title":"Terminer","instruction":"Expire sur quatre temps, puis recommence à ton rythme.","seconds":null}]'::jsonb, 'Ne retiens pas ton souffle si cela crée une gêne ; raccourcis les temps ou respire normalement.', 2),
    ('00000000-0036-4036-8000-000000000003'::uuid, 'expiration-apaisante', 'Expiration apaisante', 'breathing', 'Une pratique centrée sur une expiration légèrement plus longue, dans le confort.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Pose une main sur le ventre et relâche les épaules.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Inspire tranquillement, puis expire un peu plus longtemps.","seconds":120},{"order":3,"title":"Terminer","instruction":"Répète sans bloquer et reviens à ton souffle naturel.","seconds":null}]'::jsonb, 'L’expiration doit rester facile ; ne cherche ni profondeur ni performance.', 3),
    ('00000000-0036-4036-8000-000000000004'::uuid, 'souffle-des-vagues', 'Souffle des vagues', 'breathing', 'Laisse le souffle monter et redescendre comme une vague, sans chercher à le contrôler.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Imagine une vague qui arrive avec l’inspiration.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Laisse-la repartir avec une expiration souple.","seconds":120},{"order":3,"title":"Terminer","instruction":"Observe cinq cycles, puis desserre doucement l’attention.","seconds":null}]'::jsonb, 'Arrête si tu ressens un vertige ou un inconfort important.', 4),
    ('00000000-0036-4036-8000-000000000005'::uuid, 'respiration-des-epaules', 'Respiration des épaules', 'breathing', 'Un repère corporel simple pour desserrer les épaules au fil de quelques respirations.', 150, 'débutant', '[{"order":1,"title":"Observer","instruction":"À l’inspiration, remarque la place autour des épaules.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"À l’expiration, laisse-les descendre sans les pousser.","seconds":120},{"order":3,"title":"Terminer","instruction":"Répète lentement et garde le visage détendu.","seconds":null}]'::jsonb, 'Reste dans une amplitude confortable et évite tout mouvement douloureux.', 5),
    ('00000000-0036-4036-8000-000000000006'::uuid, 'trois-souffles-de-pause', 'Trois souffles de pause', 'breathing', 'Une micro-pratique à utiliser entre deux moments chargés de la journée.', 60, 'débutant', '[{"order":1,"title":"Observer","instruction":"Arrête-toi et sens tes pieds au sol.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Prends trois respirations calmes, sans les amplifier.","seconds":120},{"order":3,"title":"Terminer","instruction":"Choisis ensuite un geste simple pour reprendre.","seconds":null}]'::jsonb, 'Si le souffle est inconfortable, laisse-le simplement redevenir spontané.', 6),
    ('00000000-0036-4036-8000-000000000007'::uuid, 'souffle-alterne-doux', 'Souffle alterné doux', 'breathing', 'Une alternance légère de l’attention pour ralentir le rythme sans apnée ni effort.', 240, 'intermédiaire', '[{"order":1,"title":"Observer","instruction":"Inspire par le nez si c’est confortable.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Porte ton attention à droite puis à gauche du passage de l’air.","seconds":120},{"order":3,"title":"Terminer","instruction":"Laisse l’alternance disparaître et observe ton souffle.","seconds":null}]'::jsonb, 'Ne bouche jamais les voies respiratoires avec force ; respire normalement dès que nécessaire.', 7),
    ('00000000-0036-4036-8000-000000000008'::uuid, 'respirer-dans-le-dos', 'Respirer dans le dos', 'breathing', 'Une visualisation corporelle pour sentir le souffle élargir doucement l’arrière du buste.', 210, 'débutant', '[{"order":1,"title":"Observer","instruction":"Assieds-toi ou allonge-toi sans tension.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Imagine l’air qui apporte de l’espace entre les omoplates.","seconds":120},{"order":3,"title":"Terminer","instruction":"À chaque expiration, relâche le poids du dos.","seconds":null}]'::jsonb, 'La visualisation suffit ; ne cherche pas à remplir les poumons davantage.', 8),
    ('00000000-0036-4036-8000-000000000009'::uuid, 'compter-sans-forcer', 'Compter sans forcer', 'breathing', 'Compter quelques expirations pour revenir au présent, sans transformer le souffle en exercice de performance.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Compte doucement chaque expiration jusqu’à cinq.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Recommence depuis un lorsque l’attention s’éloigne.","seconds":120},{"order":3,"title":"Terminer","instruction":"Laisse le comptage et reste simplement présent.","seconds":null}]'::jsonb, 'Reviens au rythme naturel si compter devient contraignant.', 9),
    ('00000000-0036-4036-8000-000000000010'::uuid, 'respiration-du-matin', 'Respiration du matin', 'breathing', 'Un réveil respiratoire calme pour ouvrir la journée avec plus de présence.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Observe la lumière et l’air autour de toi.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Prends plusieurs inspirations souples, sans les accentuer.","seconds":120},{"order":3,"title":"Terminer","instruction":"Formule une intention simple pour les prochaines heures.","seconds":null}]'::jsonb, 'Garde une respiration naturelle et assieds-toi si tu te sens instable.', 10),
    ('00000000-0036-4036-8000-000000000011'::uuid, 'deposer-les-mains', 'Déposer les mains', 'relaxation', 'Un relâchement progressif des mains et des avant-bras après une journée de tension.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Serre très légèrement les mains, puis relâche.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Observe la différence entre tension et repos.","seconds":120},{"order":3,"title":"Terminer","instruction":"Laisse les bras peser quelques instants.","seconds":null}]'::jsonb, 'Ne serre pas les articulations et reste dans une sensation agréable.', 11),
    ('00000000-0036-4036-8000-000000000012'::uuid, 'balayage-des-appuis', 'Balayage des appuis', 'relaxation', 'Ramène ton attention vers les points de contact du corps avec le sol ou la chaise.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Sens les pieds, le bassin et le dos.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Décris mentalement les appuis sans les corriger.","seconds":120},{"order":3,"title":"Terminer","instruction":"Choisis l’appui le plus stable et repose-toi dessus.","seconds":null}]'::jsonb, 'Adapte la position pour éviter toute douleur ou engourdissement.', 12),
    ('00000000-0036-4036-8000-000000000013'::uuid, 'pause-des-machoires', 'Pause des mâchoires', 'relaxation', 'Une courte pause pour desserrer la mâchoire, la langue et le front.', 120, 'débutant', '[{"order":1,"title":"Observer","instruction":"Laisse les dents se séparer légèrement.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Pose la langue au repos et défroisse le front.","seconds":120},{"order":3,"title":"Terminer","instruction":"Expire puis reprends une expression naturelle.","seconds":null}]'::jsonb, 'Ne force pas l’ouverture de la bouche ; le relâchement doit rester subtil.', 13),
    ('00000000-0036-4036-8000-000000000014'::uuid, 'nuage-de-pensees', 'Nuage de pensées', 'relaxation', 'Observe les pensées passer sans devoir les résoudre immédiatement.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Imagine chaque pensée comme un nuage en déplacement.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Nomme doucement « pensée » lorsqu’elle arrive.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reviens au contact des pieds et de la respiration.","seconds":null}]'::jsonb, 'Si une pensée devient trop envahissante, ouvre les yeux et reviens aux sensations présentes.', 14),
    ('00000000-0036-4036-8000-000000000015'::uuid, 'relacher-le-poids', 'Relâcher le poids', 'relaxation', 'Une pratique debout pour sentir le poids descendre vers le sol et alléger la posture.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Place les pieds à largeur confortable.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Plie à peine les genoux et laisse le poids descendre.","seconds":120},{"order":3,"title":"Terminer","instruction":"Redresse-toi sans raidir le corps.","seconds":null}]'::jsonb, 'Pratique près d’un appui si ton équilibre est fragile.', 15),
    ('00000000-0036-4036-8000-000000000016'::uuid, 'regard-au-loin', 'Regard au loin', 'relaxation', 'Change de distance visuelle et offre à ton attention un horizon plus large.', 120, 'débutant', '[{"order":1,"title":"Observer","instruction":"Regarde un point proche sans le détailler.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Porte ensuite le regard vers un point plus éloigné.","seconds":120},{"order":3,"title":"Terminer","instruction":"Cligne des yeux et laisse le regard revenir naturellement.","seconds":null}]'::jsonb, 'Ne fixe pas une source lumineuse ; choisis un point confortable.', 16),
    ('00000000-0036-4036-8000-000000000017'::uuid, 'rituel-de-transition', 'Rituel de transition', 'relaxation', 'Un passage guidé entre une activité terminée et la suivante.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Nomme mentalement ce que tu viens de terminer.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Fais un geste concret : ranger, boire ou ouvrir une fenêtre.","seconds":120},{"order":3,"title":"Terminer","instruction":"Choisis une seule prochaine action.","seconds":null}]'::jsonb, 'Reste libre d’adapter ou d’écourter chaque étape.', 17),
    ('00000000-0036-4036-8000-000000000018'::uuid, 'ancrage-des-cinq-sens', 'Ancrage des cinq sens', 'relaxation', 'Utilise les sensations immédiates pour retrouver un contact simple avec l’instant.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Repère trois choses que tu vois.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Écoute deux sons puis sens un contact sur la peau.","seconds":120},{"order":3,"title":"Terminer","instruction":"Termine par une respiration et une phrase d’orientation.","seconds":null}]'::jsonb, 'Si une sensation est inconfortable, passe simplement à une autre.', 18),
    ('00000000-0036-4036-8000-000000000019'::uuid, 'etirement-du-soupir', 'Étirement du soupir', 'relaxation', 'Associe un mouvement très doux à un soupir naturel pour libérer un peu d’espace.', 150, 'débutant', '[{"order":1,"title":"Observer","instruction":"Monte les bras seulement si les épaules sont libres.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Expire en les laissant redescendre lentement.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reste immobile et remarque l’effet du mouvement.","seconds":null}]'::jsonb, 'Ne transforme pas le soupir en effort et respecte les limites du corps.', 19),
    ('00000000-0036-4036-8000-000000000020'::uuid, 'pause-avant-de-repondre', 'Pause avant de répondre', 'relaxation', 'Un sas de quelques instants pour créer un choix avant une réponse ou un message.', 90, 'débutant', '[{"order":1,"title":"Observer","instruction":"Pose le téléphone ou détourne le regard.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Prends une respiration normale et nomme ton intention.","seconds":120},{"order":3,"title":"Terminer","instruction":"Réponds avec une phrase simple ou reporte la réponse.","seconds":null}]'::jsonb, 'Cette pratique ne remplace pas une aide adaptée si la situation est urgente.', 20),
    ('00000000-0036-4036-8000-000000000021'::uuid, 'nuque-en-diagonale', 'Nuque en diagonale', 'stretching', 'Mobilise doucement la nuque par petites amplitudes, sans chercher à tirer.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Allonge le sommet du crâne.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Tourne légèrement le regard vers une épaule.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reviens au centre puis change de côté.","seconds":null}]'::jsonb, 'Arrête immédiatement en cas de douleur, vertige ou fourmillement.', 21),
    ('00000000-0036-4036-8000-000000000022'::uuid, 'poignets-apres-lecran', 'Poignets après l’écran', 'stretching', 'Une pause douce pour les poignets et les avant-bras après une activité répétitive.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Secoue les mains très légèrement.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Étends un bras et ouvre la paume sans tirer.","seconds":120},{"order":3,"title":"Terminer","instruction":"Change de côté puis laisse les bras retomber.","seconds":null}]'::jsonb, 'Ne pousse jamais jusqu’à la douleur ni aux picotements.', 22),
    ('00000000-0036-4036-8000-000000000023'::uuid, 'ouverture-des-pectoraux', 'Ouverture des pectoraux', 'stretching', 'Ouvre l’avant des épaules avec un mouvement simple et progressif.', 150, 'débutant', '[{"order":1,"title":"Observer","instruction":"Place les mains derrière le dos ou sur les hanches.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Éloigne doucement les épaules des oreilles.","seconds":120},{"order":3,"title":"Terminer","instruction":"Respire puis relâche sans rebond.","seconds":null}]'::jsonb, 'Garde les côtes détendues et réduis l’amplitude si l’épaule tire.', 23),
    ('00000000-0036-4036-8000-000000000024'::uuid, 'dos-arrondi-dos-long', 'Dos arrondi, dos long', 'stretching', 'Alterne deux formes confortables pour réveiller la mobilité de la colonne.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"À quatre appuis ou assis, arrondis doucement le dos.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Reviens vers une colonne longue sans creuser fort.","seconds":120},{"order":3,"title":"Terminer","instruction":"Répète à la respiration, sans à-coups.","seconds":null}]'::jsonb, 'Reste lent et évite la position qui provoque une douleur.', 24),
    ('00000000-0036-4036-8000-000000000025'::uuid, 'mollets-au-mur', 'Mollets au mur', 'stretching', 'Un étirement stable des mollets, pratique après être resté longtemps assis.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Place les mains contre un mur.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Recule un pied et garde son talon posé si confortable.","seconds":120},{"order":3,"title":"Terminer","instruction":"Change de côté puis marche quelques pas.","seconds":null}]'::jsonb, 'Ne force pas le talon au sol ; garde une tension légère.', 25),
    ('00000000-0036-4036-8000-000000000026'::uuid, 'flancs-en-longueur', 'Flancs en longueur', 'stretching', 'Redonne de la longueur aux côtés du corps avec une inclinaison douce.', 150, 'débutant', '[{"order":1,"title":"Observer","instruction":"Lève un bras sans hausser l’épaule.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Incline-toi légèrement vers le côté opposé.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reviens au centre et alterne lentement.","seconds":null}]'::jsonb, 'Évite de tourner le buste ou de comprimer les côtes.', 26),
    ('00000000-0036-4036-8000-000000000027'::uuid, 'hanches-assises', 'Hanches assises', 'stretching', 'Une séquence assise pour libérer doucement l’avant et l’arrière des hanches.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Pose une cheville sur l’autre cuisse si c’est confortable.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Incline le buste de quelques centimètres.","seconds":120},{"order":3,"title":"Terminer","instruction":"Change de côté et termine par deux appuis égaux.","seconds":null}]'::jsonb, 'Reste sur une chaise stable et ne pousse pas le genou.', 27),
    ('00000000-0036-4036-8000-000000000028'::uuid, 'pieds-et-chevilles', 'Pieds et chevilles', 'stretching', 'Réveille les pieds par des mouvements lents et faciles à faire assis.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Décris de petits cercles avec une cheville.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Étire les orteils puis relâche.","seconds":120},{"order":3,"title":"Terminer","instruction":"Change de pied et pose-les à plat.","seconds":null}]'::jsonb, 'Réduis l’amplitude si une articulation est sensible.', 28),
    ('00000000-0036-4036-8000-000000000029'::uuid, 'bras-au-dessus-de-la-tete', 'Bras au-dessus de la tête', 'stretching', 'Étire la ligne des bras et du buste sans chercher à cambrer.', 120, 'débutant', '[{"order":1,"title":"Observer","instruction":"Entrelace les doigts ou garde les mains séparées.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Grandis-toi vers le haut pendant quelques respirations.","seconds":120},{"order":3,"title":"Terminer","instruction":"Redescends les bras et relâche les mains.","seconds":null}]'::jsonb, 'Garde les bras dans une zone sans douleur pour les épaules.', 29),
    ('00000000-0036-4036-8000-000000000030'::uuid, 'pli-avant-soutenu', 'Pli avant soutenu', 'stretching', 'Un pli avant très modéré, avec le poids porté par une chaise ou les cuisses.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Assieds-toi au bord d’une chaise, pieds stables.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Laisse le buste s’incliner vers les cuisses, mains soutenues.","seconds":120},{"order":3,"title":"Terminer","instruction":"Remonte lentement en gardant le regard bas.","seconds":null}]'::jsonb, 'Ne descends pas bas et évite cette position si elle provoque vertige ou douleur.', 30),
    ('00000000-0036-4036-8000-000000000031'::uuid, 'cercles-d-epaules', 'Cercles d’épaules', 'mobility', 'Une routine fluide pour réveiller les épaules sans charge ni vitesse.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Monte les épaules vers les oreilles.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Fais-les rouler vers l’arrière puis vers le bas.","seconds":120},{"order":3,"title":"Terminer","instruction":"Inverse le mouvement et termine bras relâchés.","seconds":null}]'::jsonb, 'Les cercles restent petits si une épaule est sensible.', 31),
    ('00000000-0036-4036-8000-000000000032'::uuid, 'rotation-assise', 'Rotation assise', 'mobility', 'Mobilise le haut du dos depuis une chaise, avec un axe stable.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Pose les pieds au sol et allonge la colonne.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Tourne le buste vers la droite en gardant le bassin stable.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reviens au centre puis change de côté.","seconds":null}]'::jsonb, 'Tourne seulement dans l’amplitude confortable, sans tirer sur le cou.', 32),
    ('00000000-0036-4036-8000-000000000033'::uuid, 'marche-consciente', 'Marche consciente', 'mobility', 'Quelques pas lents pour reconnecter mouvement, respiration et environnement.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Marche plus lentement que d’habitude.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Sens le transfert du poids d’un pied à l’autre.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reprends ton allure naturelle en gardant cette attention.","seconds":null}]'::jsonb, 'Choisis un espace dégagé et arrête-toi si tu te sens instable.', 33),
    ('00000000-0036-4036-8000-000000000034'::uuid, 'bassin-en-huit', 'Bassin en huit', 'mobility', 'Dessine de petits huit avec le bassin pour varier la mobilité du bas du corps.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Place les pieds parallèles et les genoux souples.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Dessine un huit lent avec le bassin.","seconds":120},{"order":3,"title":"Terminer","instruction":"Inverse le sens puis reviens à l’immobilité.","seconds":null}]'::jsonb, 'Tiens-toi à un support si nécessaire et évite toute amplitude douloureuse.', 34),
    ('00000000-0036-4036-8000-000000000035'::uuid, 'chevilles-en-eveil', 'Chevilles en éveil', 'mobility', 'Une séquence simple pour remettre du mouvement dans les chevilles.', 150, 'débutant', '[{"order":1,"title":"Observer","instruction":"Lève un talon puis l’autre.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Déplace doucement le poids vers les pointes puis les talons.","seconds":120},{"order":3,"title":"Terminer","instruction":"Termine par quelques cercles contrôlés.","seconds":null}]'::jsonb, 'Reste assis si l’équilibre ou les articulations demandent plus de sécurité.', 35),
    ('00000000-0036-4036-8000-000000000036'::uuid, 'pas-lateraux-doux', 'Pas latéraux doux', 'mobility', 'Déplace-toi de côté avec attention, sans intensité sportive.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Fais un pas à droite et rapproche l’autre pied.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Répète lentement dans l’autre direction.","seconds":120},{"order":3,"title":"Terminer","instruction":"Arrête-toi, sens tes appuis et respire naturellement.","seconds":null}]'::jsonb, 'Pratique dans un espace libre, près d’un appui si besoin.', 36),
    ('00000000-0036-4036-8000-000000000037'::uuid, 'chat-qui-s-etire', 'Chat qui s’étire', 'mobility', 'Une alternance douce au sol ou sur une chaise pour délier le dos.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Allonge le dos et laisse la tête suivre le mouvement.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Arrondis doucement puis reviens vers une ligne longue.","seconds":120},{"order":3,"title":"Terminer","instruction":"Répète avec un rythme lent et régulier.","seconds":null}]'::jsonb, 'Utilise une chaise si le sol n’est pas adapté et reste sans douleur.', 37),
    ('00000000-0036-4036-8000-000000000038'::uuid, 'regard-et-nuque', 'Regard et nuque', 'mobility', 'Déplace les yeux puis la tête pour retrouver une mobilité douce du haut du corps.', 120, 'débutant', '[{"order":1,"title":"Observer","instruction":"Regarde à droite puis à gauche sans bouger la tête.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Laisse ensuite le nez suivre le regard, très peu.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reviens face à toi et cligne des yeux.","seconds":null}]'::jsonb, 'Ne fais aucun mouvement rapide et arrête en cas de vertige.', 38),
    ('00000000-0036-4036-8000-000000000039'::uuid, 'transfert-des-appuis', 'Transfert des appuis', 'mobility', 'Explore le passage du poids d’un pied à l’autre pour sentir ton équilibre.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Place les pieds sous les hanches.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Transfère doucement le poids à droite puis à gauche.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reviens au centre et sens les deux pieds.","seconds":null}]'::jsonb, 'Garde une main proche d’un support stable si nécessaire.', 39),
    ('00000000-0036-4036-8000-000000000040'::uuid, 'reveil-du-dos', 'Réveil du dos', 'mobility', 'Une séquence debout courte pour remettre de la fluidité avant de reprendre sa journée.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Allonge les bras vers l’avant puis relâche.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Tourne doucement les épaules et le haut du dos.","seconds":120},{"order":3,"title":"Terminer","instruction":"Secoue les mains et retrouve une posture naturelle.","seconds":null}]'::jsonb, 'Reste dans une amplitude confortable et évite les mouvements brusques.', 40),
    ('00000000-0036-4036-8000-000000000041'::uuid, 'descente-du-soir', 'Descente du soir', 'sleep', 'Un rituel calme pour ralentir progressivement avant la nuit.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Baisse la lumière et éloigne les notifications.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Respire naturellement en relâchant le visage.","seconds":120},{"order":3,"title":"Terminer","instruction":"Choisis une activité calme pour la suite.","seconds":null}]'::jsonb, 'Si tu t’endors, laisse simplement la pratique se terminer.', 41),
    ('00000000-0036-4036-8000-000000000042'::uuid, 'jambes-legères-au-lit', 'Jambes légères au lit', 'sleep', 'Une mobilisation minimale des jambes pour quitter la journée sans effort.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Allonge les jambes et observe leur poids.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Bouge les chevilles puis laisse-les immobiles.","seconds":120},{"order":3,"title":"Terminer","instruction":"Sens le matelas soutenir tout le corps.","seconds":null}]'::jsonb, 'Reste dans une position confortable et arrête si une douleur apparaît.', 42),
    ('00000000-0036-4036-8000-000000000043'::uuid, 'compter-les-expirations', 'Compter les expirations', 'sleep', 'Un comptage souple pour accompagner l’attention vers un rythme plus tranquille.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Commence à compter chaque expiration de un à dix.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Repars doucement à un si tu te disperses.","seconds":120},{"order":3,"title":"Terminer","instruction":"Laisse ensuite les nombres disparaître.","seconds":null}]'::jsonb, 'Ne retiens pas ton souffle et abandonne le comptage s’il devient contraignant.', 43),
    ('00000000-0036-4036-8000-000000000044'::uuid, 'ecran-vers-silence', 'De l’écran au silence', 'sleep', 'Une transition concrète pour déposer les sollicitations numériques avant le coucher.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Pose l’écran hors de portée.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Note mentalement une chose à reprendre demain.","seconds":120},{"order":3,"title":"Terminer","instruction":"Installe-toi dans une lumière plus douce.","seconds":null}]'::jsonb, 'Adapte la durée au réel de ta soirée, sans rechercher la perfection.', 44),
    ('00000000-0036-4036-8000-000000000045'::uuid, 'relaxation-des-pieds', 'Relaxation des pieds', 'sleep', 'Ramène l’attention vers les pieds et laisse le reste du corps se déposer.', 360, 'débutant', '[{"order":1,"title":"Observer","instruction":"Sens les talons et les orteils.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Imagine les pieds devenir lourds et chauds.","seconds":120},{"order":3,"title":"Terminer","instruction":"Laisse la sensation se diffuser sans la forcer.","seconds":null}]'::jsonb, 'Ne contracte pas les muscles si cela crée une gêne.', 45),
    ('00000000-0036-4036-8000-000000000046'::uuid, 'le-jour-se-termine', 'Le jour se termine', 'sleep', 'Une clôture douce pour reconnaître ce qui est fait et laisser le reste attendre demain.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Rappelle-toi une chose accomplie aujourd’hui.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Reconnais une chose que tu peux laisser en suspens.","seconds":120},{"order":3,"title":"Terminer","instruction":"Dis-toi que la suite pourra reprendre demain.","seconds":null}]'::jsonb, 'Si une inquiétude revient, note-la pour plus tard plutôt que de lutter.', 46),
    ('00000000-0036-4036-8000-000000000047'::uuid, 'respiration-allongee', 'Respiration allongée', 'sleep', 'Allonge-toi et accompagne quelques respirations sans chercher à les approfondir.', 300, 'débutant', '[{"order":1,"title":"Observer","instruction":"Installe la nuque et les jambes confortablement.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Observe l’air entrer et sortir sans le diriger.","seconds":120},{"order":3,"title":"Terminer","instruction":"Laisse le souffle redevenir totalement spontané.","seconds":null}]'::jsonb, 'Garde ton rythme naturel et arrête si tu ressens un inconfort.', 47),
    ('00000000-0036-4036-8000-000000000048'::uuid, 'scan-du-lit', 'Scan du lit', 'sleep', 'Parcours les zones soutenues par le lit pour inviter le corps au repos.', 420, 'débutant', '[{"order":1,"title":"Observer","instruction":"Commence par l’arrière de la tête et les épaules.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Descends vers le dos, le bassin et les jambes.","seconds":120},{"order":3,"title":"Terminer","instruction":"Termine par la sensation globale du corps soutenu.","seconds":null}]'::jsonb, 'Modifie ta position si une zone devient douloureuse.', 48),
    ('00000000-0036-4036-8000-000000000049'::uuid, 'phrase-de-deconnexion', 'Phrase de déconnexion', 'sleep', 'Une phrase courte et répétée pour marquer la fin des activités du jour.', 180, 'débutant', '[{"order":1,"title":"Observer","instruction":"Choisis : « Pour ce soir, j’en fais assez ».","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Répète-la doucement à chaque expiration.","seconds":120},{"order":3,"title":"Terminer","instruction":"Laisse la phrase s’éloigner quand le sommeil arrive.","seconds":null}]'::jsonb, 'Choisis une formulation qui te convient, sans obligation de résultat.', 49),
    ('00000000-0036-4036-8000-000000000050'::uuid, 'matin-en-reserve', 'Matin en réserve', 'sleep', 'Dépose les préoccupations du lendemain dans une intention simple avant de dormir.', 240, 'débutant', '[{"order":1,"title":"Observer","instruction":"Visualise demain comme une page encore fermée.","seconds":30},{"order":2,"title":"Pratiquer","instruction":"Garde une seule priorité, pas toute la liste.","seconds":120},{"order":3,"title":"Terminer","instruction":"Reviens au contact du lit et laisse la soirée finir.","seconds":null}]'::jsonb, 'Si une tâche importante revient, écris-la brièvement puis reprends la détente.', 50)
ON CONFLICT (slug) DO NOTHING;
